alias aws='docker run --rm -ti -v ~/.aws:/root/.aws amazon/aws-cli'
alias oci='docker run --rm -it -v ~/.oci:/oracle/.oci ghcr.io/oracle/oci-cli'
alias acme.sh='docker run --rm -it -v ~/.acme.sh:/acme.sh neilpang/acme.sh'
alias kubectl='docker run -it --rm --net=host -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace -v $HOME/.kube:/root/.kube -v $HOME/.ssh:/root/.ssh --workdir /workspace ghcr.io/harrytang/devops-tools kubectl'
alias kubeseal='docker run -it --rm --net=host -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace -v $HOME/.kube:/root/.kube -v $HOME/.ssh:/root/.ssh --workdir /workspace ghcr.io/harrytang/devops-tools kubeseal'
alias helm='docker run -it --rm --net=host -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace -v $HOME/.kube:/root/.kube -v $HOME/.ssh:/root/.ssh --workdir /workspace ghcr.io/harrytang/devops-tools helm'
alias devops='docker run -it --rm --net=host -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace -v $HOME/.kube:/root/.kube -v $HOME/.ssh:/root/.ssh -v $HOME/.gitconfig:/root/.gitconfig --workdir /workspace ghcr.io/harrytang/devops-tools:latest ssh-agent /bin/bash'